import { ThemeProvider } from '@/providers/ThemeProvider';
import { Poppins } from 'next/font/google';
import localFont from 'next/font/local';
import '@/styles/tokens.css';
import '@/styles/global.css';
import QueryProvider from '@/providers/QueryProvider';
import { getLayout } from '@/lib/wordpress/data-fetching/queries';
import Header from '@/components/layout/Header/Header';
import Footer from '@/components/layout/Footer/Footer';

// Font for text
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  variable: '--font-poppins',
  display: 'swap',
});

// Font for titles
const ardelaEdge = localFont({
  src: '../../public/fonts/ARDELA_EDGE_X01_Variable.ttf',
  variable: '--font-ardela',
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: [{ url: '/favicon.ico' }, { url: '/icon.png', type: 'image/png' }],
  },
};

export default async function RootLayout({ children }) {
  const layout = await getLayout();

  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${poppins.variable} ${ardelaEdge.variable}`}
    >
      <body>
        <QueryProvider>
          <ThemeProvider>
            <Header header={layout?.header} />
            {children}
            <Footer footer={layout?.footer} />
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
