export const endpoints = {
  pages: '/pages',
  services: '/service',
  zones: '/services-zone',
  events: '/event',
  faqs: '/faq',
  partners: '/partner',
  podcasts: '/podcats',
  teamMembers: '/team-member',
  testimonials: '/testimonial',
  videos: '/video',

  pagesWithLimit: (limit) => `/pages?per_page=${limit}`,
  servicesWithLimit: (limit) => `/service?per_page=${limit}`,
  zonesWithLimit: (limit) => `/services-zone?per_page=${limit}`,
  eventsWithLimit: (limit) => `/event?per_page=${limit}`,
  faqsWithLimit: (limit) => `/faq?per_page=${limit}`,
  partnersWithLimit: (limit) => `/partner?per_page=${limit}`,
  podcastsWithLimit: (limit) => `/podcats?per_page=${limit}`,
  teamMembersWithLimit: (limit) => `/team-member?per_page=${limit}`,
  testimonialsWithLimit: (limit) => `/testimonial?per_page=${limit}`,
  videosWithLimit: (limit) => `/video?per_page=${limit}`,

  pageBySlug: (slug) => `/pages?slug=${slug}`,
  serviceBySlug: (slug) => `/service?slug=${slug}`,
  zoneBySlug: (slug) => `/services-zone?slug=${slug}`,
  companyLogoBySlug: (slug) => `/company-logo?slug=${slug}`,
  eventBySlug: (slug) => `/event?slug=${slug}`,
  faqBySlug: (slug) => `/faq?slug=${slug}`,
  partnerBySlug: (slug) => `/partner?slug=${slug}`,
  podcatBySlug: (slug) => `/podcats?slug=${slug}`,
  teamMemberBySlug: (slug) => `/team-member?slug=${slug}`,
  testimonialBySlug: (slug) => `/testimonial?slug=${slug}`,
  videoBySlug: (slug) => `/video?slug=${slug}`,

  pageById: (id) => `/pages/${id}`,
  serviceById: (id) => `/service/${id}`,
  zoneById: (id) => `/services-zone/${id}`,
  companyLogoById: (id) => `/company-logo/${id}`,
  eventById: (id) => `/event/${id}`,
  faqById: (id) => `/faq/${id}`,
  partnerById: (id) => `/partner/${id}`,
  podcatById: (id) => `/podcats/${id}`,
  testimonialById: (id) => `/testimonial/${id}`,
  videoById: (id) => `/video/${id}`,

  // Global Site Data
  headerFooterBySlug: '/pages?slug=header-and-footer',
  headerFooterById: '/pages/797',
};
